travis:
  secure:
    BINSTAR_TOKEN: pzuqPyIU31bnysDpnaq6oyjy4ZVJk4R8UGvhKhHVhJ0p8nEd5Tv5aylrYXrbY1baEEFCD6iKbiWLo7/GU7NpS6ROjfzUbim+fDbSeBvXJPgSDUVkPAqZsNnNs9sfZBckh7pwGOuXLjNpgWbMwtuuOwaE5ASdMVFEq7DQFxmsmI3L9dUqOjvCE3vG3t8REcSUaJe4WBs4OPOu8T/bBBvjpYma8Flba1idc25U3ZNPSl9eZocLKRtpWbBAYAVdX8ElZM7pyQCtafb7A9COFAwKWCDjcLA5g8nzJAAvY1q+hC41MOkzxosA6d+PC4qPnmV+Eq8l4WFnInCh+pn6f3xGxScJpY2iF6cjUSWr1wGXondiigGtF0Zsps/KPi9nlHOVFT3u/zjXzhix2fweJJUPbLoCYrjHLLL2I+OYQBZ6q2FHpTw63QnbG95oOM+jP6tmq2ZvfUOxx4r+25RARKQhCuFwqwVlBQu0jcYPuHt9JjVs7eOZ3MALPNTMhqgwce4/kimlYgHWlGhTQbMH06r0g4SkMlSuLQCtcfLi1c082T5ss7ZhtQ0qySgPmXzYUByfzxyhVUt6CGRxQtWmHRLlyfk5KQsi9VWcoeT/lpgR6AjlmfArwcAeWClCZOVltmsg3Lz19enldN76DNr5gknKIV1/6GuUeK/u51nT8J/Gv3Q=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
