travis:
  secure:
    BINSTAR_TOKEN: qBDbpRkXTk9rYa0jdv3575iK36Fv8rY+5JH977HHrXv72LudvcmMR1Lq6vZ/YXaD8pVXe2L03t4iwglHqAIioOrvUn6IAs9GPEk4NUfSIzk3755hQOv1NPjiy0HKHk6pPgc/rQp6qISxFrzv3f+GzFgN/m/5WGX8ZMZuj0sJFtu8TxhfJfj1Tkj1WvYIW83unsA6+WkKBwLG7hBXae0zpcF+hSgEmOf1hsoGAfNKQY/E2EsGJ6hxJwc0zjhfxPZOWF4OEncZ/3AwHrbA9Fl52NunxiW4PgDZ6xwPQHPvvpbncwxMwZFHbC8DTIvUn7dQJQCgODdbD/8uOz9OsOyRe8mn36kY2bkZdq0GAG46+M/3kl+wJuMgaqlBuhzOuzW0uhWzYk/YQYBikTVZvv/dV8xcdWOUoJXYZOVwwJlpZypHf2y9f1CwZYxWZBWWoW1I8CLGLTyIjDhyPR9tpH5wn92C44wbPUO7K/VoUuKawOZVTivk02iRvSgmUufL1TngrU8EdUU8yRD5bZ7lNdGMQ/WyWEWulNnlVxvvC7a2mDTgz9aAcSG390xzakALd5v1Hou0aCYC2kr/vQUvvvfbF+6iS0hFRC23dtmmiiCFk2tzySWuFTSk3gVyRZ4fvc8Zg33kXxh8YOzQcXA1gs4sjl/aLsI1RvtUqWt/A4Tpes8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
